### GET request to example server
POST http://localhost:8080/patients
Content-Type: application/json

{
  "name": "Jackson",
  "email": "test@example.com",
  "address": "123 main st",
  "dateOfBirth": "1996-01-01",
  "registeredDate": "2025-01-01"
}

###